name: CI

on:
  pull_request:
    branches: [dev]
    paths-ignore:
      - '**.md'

permissions:
  contents: read

env:
  NODE_VERSION: '24.5.0'
  YARN_VERSION: '4.9.2'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Enable Corepack & set Yarn
        run: |
          corepack enable
          corepack prepare yarn@${{ env.YARN_VERSION }} --activate

      - id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            **/node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn install --immutable

  check:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: |
          corepack enable
          corepack prepare yarn@${{ env.YARN_VERSION }} --activate

      - run: yarn install --immutable

      - name: Check formatting
        run: yarn check

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: |
          corepack enable
          corepack prepare yarn@${{ env.YARN_VERSION }} --activate

      - run: yarn install --immutable

      - name: Build shared packages
        run: yarn build:shared

      - name: Build
        run: yarn build

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: |
          corepack enable
          corepack prepare yarn@${{ env.YARN_VERSION }} --activate

      - run: yarn install --immutable

      - name: Build shared packages
        run: yarn build:shared

      - name: Unit tests with coverage
        run: yarn test --coverage

  audit:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: |
          corepack enable
          corepack prepare yarn@${{ env.YARN_VERSION }} --activate

      - run: yarn install --immutable

      - name: Check for security vulnerabilities
        run: yarn npm audit
